"""Image URL to phonebook

Revision ID: 81f1162f44db
Revises: 170427e03abe
Create Date: 2022-03-31 21:18:45.996452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81f1162f44db'
down_revision = '170427e03abe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone_book', sa.Column('image_url', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone_book', 'image_url')
    # ### end Alembic commands ###
